name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      - name: Build with Maven Wrapper
        run: ./mvnw -B package

  publish:
      
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Stage 
        run: mvn --batch-mode --update-snapshots verify

      - name: Create Staging folder and copy files
        run: mkdir staging && cp target/*.jar staging

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          